version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Move to client directory
          command: cd ./client
      - run:
          name: Install npm dependencies
          command: npm install --save
      - run:
          name: Run unit tests
          command: npm run test:unit
workflows:
  build_test:
    jobs:
      - run_test
